Algoritmo "semnome"
// 
//  

Var
// Seção de Declarações das variáveis:
vet: vetor [1..20] de inteiro
matriz: vetor [1..4, 1..5] de inteiro
i, j: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para i de 1 ate 4 faca
para j de 1 ate 5 faca
escreva ("Digite qualquer número aí [",i,",",j,"]:")
leia (matriz[i,j])
fimpara
fimpara
para i de 1 ate 4 faca
para j de 1 ate 5 faca
escreva (matriz[i,j])
fimpara
escreval ()
fimpara
Fimalgoritmo